export const ADD_MOVIE = 'ADD_MOVIE';
export const RECEIVE_MOVIE = 'RECEIVE_MOVIE';
export const DELETE_MOVIE = 'ADD_MOVIE';
export const MARK_MOVIE_AS_WATCHED = 'MARK_MOVIE_AS_WATCHED';
export const MARK_MOVIE_AS_UNWATCHED = 'MARK_MOVIE_AS_UNWATCHED';
export const FETCH_INITIAL_MOVIES = 'FETCH_INITIAL_MOVIES';
export const RECEIVE_INITIAL_MOVIES = 'RECEIVE_INITIAL_MOVIES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
